import type { Surah } from "./types";

export const SURAHS: Surah[] = [
  { number: 1, name: "Al-Fatiha", nameArabic: "الفاتحة", nameTranslation: "المفتاح", revelation: "Meccan", versesCount: 7, pages: [1, 1], juz: [1] },
  { number: 2, name: "Al-Baqarah", nameArabic: "البقرة", nameTranslation: "البقرة", revelation: "Medinan", versesCount: 286, pages: [2, 49], juz: [1,2,3] },
  { number: 3, name: "Ali 'Imran", nameArabic: "آل عمران", nameTranslation: "عمران", revelation: "Medinan", versesCount: 200, pages: [50, 76], juz: [3,4] },
  { number: 4, name: "An-Nisa", nameArabic: "النساء", nameTranslation: "النساء", revelation: "Medinan", versesCount: 176, pages: [77, 106], juz: [4,5,6] },
  { number: 5, name: "Al-Ma'idah", nameArabic: "المائدة", nameTranslation: "المائدة", revelation: "Medinan", versesCount: 120, pages: [106, 127], juz: [6,7] },
  { number: 6, name: "Al-An'am", nameArabic: "الأنعام", nameTranslation: "الأنعام", revelation: "Meccan", versesCount: 165, pages: [128, 150], juz: [7,8] },
  { number: 7, name: "Al-A'raf", nameArabic: "الأعراف", nameTranslation: "الأعراف", revelation: "Meccan", versesCount: 206, pages: [151, 176], juz: [8,9] },
  { number: 8, name: "Al-Anfal", nameArabic: "الأنفال", nameTranslation: "الأنفال", revelation: "Medinan", versesCount: 75, pages: [177, 186], juz: [9,10] },
  { number: 9, name: "At-Tawbah", nameArabic: "التوبة", nameTranslation: "التوبة", revelation: "Medinan", versesCount: 129, pages: [187, 207], juz: [10,11] },
  { number: 10, name: "Yunus", nameArabic: "يونس", nameTranslation: "يونس", revelation: "Meccan", versesCount: 109, pages: [208, 221], juz: [11] },
  { number: 11, name: "Hud", nameArabic: "هود", nameTranslation: "هود", revelation: "Meccan", versesCount: 123, pages: [221, 235], juz: [11,12] },
  { number: 12, name: "Yusuf", nameArabic: "يوسف", nameTranslation: "يوسف", revelation: "Meccan", versesCount: 111, pages: [235, 248], juz: [12,13] },
  { number: 13, name: "Ar-Ra'd", nameArabic: "الرعد", nameTranslation: "الرعد", revelation: "Medinan", versesCount: 43, pages: [249, 255], juz: [13] },
  { number: 14, name: "Ibrahim", nameArabic: "إبراهيم", nameTranslation: "إبراهيم", revelation: "Meccan", versesCount: 52, pages: [255, 261], juz: [13] },
  { number: 15, name: "Al-Hijr", nameArabic: "الحجر", nameTranslation: "الحجر", revelation: "Meccan", versesCount: 99, pages: [262, 267], juz: [14] },
  { number: 16, name: "An-Nahl", nameArabic: "النحل", nameTranslation: "النحل", revelation: "Meccan", versesCount: 128, pages: [267, 281], juz: [14] },
  { number: 17, name: "Al-Isra", nameArabic: "الإسراء", nameTranslation: "الإسراء", revelation: "Meccan", versesCount: 111, pages: [282, 293], juz: [15] },
  { number: 18, name: "Al-Kahf", nameArabic: "الكهف", nameTranslation: "الكهف", revelation: "Meccan", versesCount: 110, pages: [293, 304], juz: [15,16] },
  { number: 19, name: "Maryam", nameArabic: "مريم", nameTranslation: "مريم", revelation: "Meccan", versesCount: 98, pages: [305, 312], juz: [16] },
  { number: 20, name: "Ta-Ha", nameArabic: "طه", nameTranslation: "طه", revelation: "Meccan", versesCount: 135, pages: [312, 321], juz: [16] },
  { number: 21, name: "Al-Anbiya", nameArabic: "الأنبياء", nameTranslation: "الأنبياء", revelation: "Meccan", versesCount: 112, pages: [322, 331], juz: [17] },
  { number: 22, name: "Al-Hajj", nameArabic: "الحج", nameTranslation: "الحج", revelation: "Medinan", versesCount: 78, pages: [332, 341], juz: [17] },
  { number: 23, name: "Al-Mu'minun", nameArabic: "المؤمنون", nameTranslation: "المؤمنون", revelation: "Meccan", versesCount: 118, pages: [342, 349], juz: [18] },
  { number: 24, name: "An-Nur", nameArabic: "النور", nameTranslation: "النور", revelation: "Medinan", versesCount: 64, pages: [350, 359], juz: [18] },
  { number: 25, name: "Al-Furqan", nameArabic: "الفرقان", nameTranslation: "الفرقان", revelation: "Meccan", versesCount: 77, pages: [359, 366], juz: [18,19] },
  { number: 26, name: "Ash-Shu'ara", nameArabic: "الشعراء", nameTranslation: "الشعراء", revelation: "Meccan", versesCount: 227, pages: [367, 376], juz: [19] },
  { number: 27, name: "An-Naml", nameArabic: "النمل", nameTranslation: "النمل", revelation: "Meccan", versesCount: 93, pages: [377, 385], juz: [19,20] },
  { number: 28, name: "Al-Qasas", nameArabic: "القصص", nameTranslation: "القصص", revelation: "Meccan", versesCount: 88, pages: [385, 396], juz: [20] },
  { number: 29, name: "Al-'Ankabut", nameArabic: "العنكبوت", nameTranslation: "العنكبوت", revelation: "Meccan", versesCount: 69, pages: [396, 404], juz: [20,21] },
  { number: 30, name: "Ar-Rum", nameArabic: "الروم", nameTranslation: "الروم", revelation: "Meccan", versesCount: 60, pages: [404, 410], juz: [21] },
  { number: 31, name: "Luqman", nameArabic: "لقمان", nameTranslation: "لقمان", revelation: "Meccan", versesCount: 34, pages: [411, 414], juz: [21] },
  { number: 32, name: "As-Sajdah", nameArabic: "السجدة", nameTranslation: "السجدة", revelation: "Meccan", versesCount: 30, pages: [415, 417], juz: [21] },
  { number: 33, name: "Al-Ahzab", nameArabic: "الأحزاب", nameTranslation: "الأحزاب", revelation: "Medinan", versesCount: 73, pages: [418, 427], juz: [21,22] },
  { number: 34, name: "Saba", nameArabic: "سبأ", nameTranslation: "سبأ", revelation: "Meccan", versesCount: 54, pages: [428, 434], juz: [22] },
  { number: 35, name: "Fatir", nameArabic: "فاطر", nameTranslation: "فاطر", revelation: "Meccan", versesCount: 45, pages: [434, 440], juz: [22] },
  { number: 36, name: "Ya-Sin", nameArabic: "يس", nameTranslation: "يس", revelation: "Meccan", versesCount: 83, pages: [440, 445], juz: [22,23] },
  { number: 37, name: "As-Saffat", nameArabic: "الصافات", nameTranslation: "الصافات", revelation: "Meccan", versesCount: 182, pages: [446, 452], juz: [23] },
  { number: 38, name: "Sad", nameArabic: "ص", nameTranslation: "ص", revelation: "Meccan", versesCount: 88, pages: [453, 458], juz: [23] },
  { number: 39, name: "Az-Zumar", nameArabic: "الزمر", nameTranslation: "الزمر", revelation: "Meccan", versesCount: 75, pages: [458, 467], juz: [23,24] },
  { number: 40, name: "Ghafir", nameArabic: "غافر", nameTranslation: "غافر", revelation: "Meccan", versesCount: 85, pages: [467, 476], juz: [24] },
  { number: 41, name: "Fussilat", nameArabic: "فصلت", nameTranslation: "فصلت", revelation: "Meccan", versesCount: 54, pages: [477, 482], juz: [24,25] },
  { number: 42, name: "Ash-Shura", nameArabic: "الشورى", nameTranslation: "الشورى", revelation: "Meccan", versesCount: 53, pages: [483, 489], juz: [25] },
  { number: 43, name: "Az-Zukhruf", nameArabic: "الزخرف", nameTranslation: "الزخرف", revelation: "Meccan", versesCount: 89, pages: [489, 495], juz: [25] },
  { number: 44, name: "Ad-Dukhan", nameArabic: "الدخان", nameTranslation: "الدخان", revelation: "Meccan", versesCount: 59, pages: [496, 498], juz: [25] },
  { number: 45, name: "Al-Jathiyah", nameArabic: "الجاثية", nameTranslation: "الجاثية", revelation: "Meccan", versesCount: 37, pages: [499, 502], juz: [25] },
  { number: 46, name: "Al-Ahqaf", nameArabic: "الأحقاف", nameTranslation: "الأحقاف", revelation: "Meccan", versesCount: 35, pages: [502, 506], juz: [26] },
  { number: 47, name: "Muhammad", nameArabic: "محمد", nameTranslation: "محمد", revelation: "Medinan", versesCount: 38, pages: [507, 510], juz: [26] },
  { number: 48, name: "Al-Fath", nameArabic: "الفتح", nameTranslation: "الفتح", revelation: "Medinan", versesCount: 29, pages: [511, 515], juz: [26] },
  { number: 49, name: "Al-Hujurat", nameArabic: "الحجرات", nameTranslation: "الحجرات", revelation: "Medinan", versesCount: 18, pages: [515, 517], juz: [26] },
  { number: 50, name: "Qaf", nameArabic: "ق", nameTranslation: "ق", revelation: "Meccan", versesCount: 45, pages: [518, 520], juz: [26] },
  { number: 51, name: "Adh-Dhariyat", nameArabic: "الذاريات", nameTranslation: "الذاريات", revelation: "Meccan", versesCount: 60, pages: [520, 523], juz: [26,27] },
  { number: 52, name: "At-Tur", nameArabic: "الطور", nameTranslation: "الطور", revelation: "Meccan", versesCount: 49, pages: [523, 525], juz: [27] },
  { number: 53, name: "An-Najm", nameArabic: "النجم", nameTranslation: "النجم", revelation: "Meccan", versesCount: 62, pages: [526, 528], juz: [27] },
  { number: 54, name: "Al-Qamar", nameArabic: "القمر", nameTranslation: "القمر", revelation: "Meccan", versesCount: 55, pages: [528, 531], juz: [27] },
  { number: 55, name: "Ar-Rahman", nameArabic: "الرحمن", nameTranslation: "الرحمن", revelation: "Medinan", versesCount: 78, pages: [531, 534], juz: [27] },
  { number: 56, name: "Al-Waqi'ah", nameArabic: "الواقعة", nameTranslation: "الواقعة", revelation: "Meccan", versesCount: 96, pages: [534, 537], juz: [27] },
  { number: 57, name: "Al-Hadid", nameArabic: "الحديد", nameTranslation: "الحديد", revelation: "Medinan", versesCount: 29, pages: [537, 541], juz: [27] },
  { number: 58, name: "Al-Mujadila", nameArabic: "المجادلة", nameTranslation: "المجادلة", revelation: "Medinan", versesCount: 22, pages: [542, 545], juz: [28] },
  { number: 59, name: "Al-Hashr", nameArabic: "الحشر", nameTranslation: "الحشر", revelation: "Medinan", versesCount: 24, pages: [545, 548], juz: [28] },
  { number: 60, name: "Al-Mumtahanah", nameArabic: "الممتحنة", nameTranslation: "الممتحنة", revelation: "Medinan", versesCount: 13, pages: [549, 551], juz: [28] },
  { number: 61, name: "As-Saf", nameArabic: "الصف", nameTranslation: "الصف", revelation: "Medinan", versesCount: 14, pages: [551, 552], juz: [28] },
  { number: 62, name: "Al-Jumu'ah", nameArabic: "الجمعة", nameTranslation: "الجمعة", revelation: "Medinan", versesCount: 11, pages: [553, 554], juz: [28] },
  { number: 63, name: "Al-Munafiqun", nameArabic: "المنافقون", nameTranslation: "المنافقون", revelation: "Medinan", versesCount: 11, pages: [554, 555], juz: [28] },
  { number: 64, name: "At-Taghabun", nameArabic: "التغابن", nameTranslation: "التغابن", revelation: "Medinan", versesCount: 18, pages: [556, 557], juz: [28] },
  { number: 65, name: "At-Talaq", nameArabic: "الطلاق", nameTranslation: "الطلاق", revelation: "Medinan", versesCount: 12, pages: [558, 559], juz: [28] },
  { number: 66, name: "At-Tahrim", nameArabic: "التحريم", nameTranslation: "التحريم", revelation: "Medinan", versesCount: 12, pages: [560, 561], juz: [28] },
  { number: 67, name: "Al-Mulk", nameArabic: "الملك", nameTranslation: "الملك", revelation: "Meccan", versesCount: 30, pages: [562, 564], juz: [29] },
  { number: 68, name: "Al-Qalam", nameArabic: "القلم", nameTranslation: "القلم", revelation: "Meccan", versesCount: 52, pages: [564, 566], juz: [29] },
  { number: 69, name: "Al-Haqqah", nameArabic: "الحاقة", nameTranslation: "الحاقة", revelation: "Meccan", versesCount: 52, pages: [566, 568], juz: [29] },
  { number: 70, name: "Al-Ma'arij", nameArabic: "المعارج", nameTranslation: "المعارج", revelation: "Meccan", versesCount: 44, pages: [568, 570], juz: [29] },
  { number: 71, name: "Nuh", nameArabic: "نوح", nameTranslation: "نوح", revelation: "Meccan", versesCount: 28, pages: [570, 571], juz: [29] },
  { number: 72, name: "Al-Jinn", nameArabic: "الجن", nameTranslation: "الجن", revelation: "Meccan", versesCount: 28, pages: [572, 573], juz: [29] },
  { number: 73, name: "Al-Muzzammil", nameArabic: "المزمل", nameTranslation: "المزمل", revelation: "Meccan", versesCount: 20, pages: [574, 575], juz: [29] },
  { number: 74, name: "Al-Muddaththir", nameArabic: "المدثر", nameTranslation: "المدثر", revelation: "Meccan", versesCount: 56, pages: [575, 577], juz: [29] },
  { number: 75, name: "Al-Qiyamah", nameArabic: "القيامة", nameTranslation: "القيامة", revelation: "Meccan", versesCount: 40, pages: [577, 578], juz: [29] },
  { number: 76, name: "Al-Insan", nameArabic: "الإنسان", nameTranslation: "الإنسان", revelation: "Medinan", versesCount: 31, pages: [578, 580], juz: [29] },
  { number: 77, name: "Al-Mursalat", nameArabic: "المرسلات", nameTranslation: "المرسلات", revelation: "Meccan", versesCount: 50, pages: [580, 581], juz: [29] },
  { number: 78, name: "An-Naba", nameArabic: "النبأ", nameTranslation: "النبأ", revelation: "Meccan", versesCount: 40, pages: [582, 583], juz: [30] },
  { number: 79, name: "An-Nazi'at", nameArabic: "النازعات", nameTranslation: "النازعات", revelation: "Meccan", versesCount: 46, pages: [583, 584], juz: [30] },
  { number: 80, name: "Abasa", nameArabic: "عبس", nameTranslation: "عبس", revelation: "Meccan", versesCount: 42, pages: [585, 585], juz: [30] },
  { number: 81, name: "At-Takwir", nameArabic: "التكوير", nameTranslation: "التكوير", revelation: "Meccan", versesCount: 29, pages: [586, 586], juz: [30] },
  { number: 82, name: "Al-Infitar", nameArabic: "الانفطار", nameTranslation: "الانفطار", revelation: "Meccan", versesCount: 19, pages: [587, 587], juz: [30] },
  { number: 83, name: "Al-Mutaffifin", nameArabic: "المطففين", nameTranslation: "المطففين", revelation: "Meccan", versesCount: 36, pages: [587, 589], juz: [30] },
  { number: 84, name: "Al-Inshiqaq", nameArabic: "الانشقاق", nameTranslation: "الانشقاق", revelation: "Meccan", versesCount: 25, pages: [589, 590], juz: [30] },
  { number: 85, name: "Al-Buruj", nameArabic: "البروج", nameTranslation: "البروج", revelation: "Meccan", versesCount: 22, pages: [590, 591], juz: [30] },
  { number: 86, name: "At-Tariq", nameArabic: "الطارق", nameTranslation: "الطارق", revelation: "Meccan", versesCount: 17, pages: [591, 591], juz: [30] },
  { number: 87, name: "Al-A'la", nameArabic: "الأعلى", nameTranslation: "الأعلى", revelation: "Meccan", versesCount: 19, pages: [591, 592], juz: [30] },
  { number: 88, name: "Al-Ghashiyah", nameArabic: "الغاشية", nameTranslation: "الغاشية", revelation: "Meccan", versesCount: 26, pages: [592, 592], juz: [30] },
  { number: 89, name: "Al-Fajr", nameArabic: "الفجر", nameTranslation: "الفجر", revelation: "Meccan", versesCount: 30, pages: [593, 594], juz: [30] },
  { number: 90, name: "Al-Balad", nameArabic: "البلد", nameTranslation: "البلد", revelation: "Meccan", versesCount: 20, pages: [594, 594], juz: [30] },
  { number: 91, name: "Ash-Shams", nameArabic: "الشمس", nameTranslation: "الشمس", revelation: "Meccan", versesCount: 15, pages: [595, 595], juz: [30] },
  { number: 92, name: "Al-Layl", nameArabic: "الليل", nameTranslation: "الليل", revelation: "Meccan", versesCount: 21, pages: [595, 596], juz: [30] },
  { number: 93, name: "Ad-Duha", nameArabic: "الضحى", nameTranslation: "الضحى", revelation: "Meccan", versesCount: 11, pages: [596, 596], juz: [30] },
  { number: 94, name: "Ash-Sharh", nameArabic: "الشرح", nameTranslation: "الشرح", revelation: "Meccan", versesCount: 8, pages: [596, 596], juz: [30] },
  { number: 95, name: "At-Tin", nameArabic: "التين", nameTranslation: "التين", revelation: "Meccan", versesCount: 8, pages: [597, 597], juz: [30] },
  { number: 96, name: "Al-Alaq", nameArabic: "العلق", nameTranslation: "العلق", revelation: "Meccan", versesCount: 19, pages: [597, 597], juz: [30] },
  { number: 97, name: "Al-Qadr", nameArabic: "القدر", nameTranslation: "القدر", revelation: "Meccan", versesCount: 5, pages: [598, 598], juz: [30] },
  { number: 98, name: "Al-Bayyinah", nameArabic: "البينة", nameTranslation: "البينة", revelation: "Medinan", versesCount: 8, pages: [598, 599], juz: [30] },
  { number: 99, name: "Az-Zalzalah", nameArabic: "الزلزلة", nameTranslation: "الزلزلة", revelation: "Medinan", versesCount: 8, pages: [599, 599], juz: [30] },
  { number: 100, name: "Al-Adiyat", nameArabic: "العاديات", nameTranslation: "العاديات", revelation: "Meccan", versesCount: 11, pages: [599, 600], juz: [30] },
  { number: 101, name: "Al-Qari'ah", nameArabic: "القارعة", nameTranslation: "القارعة", revelation: "Meccan", versesCount: 11, pages: [600, 600], juz: [30] },
  { number: 102, name: "At-Takathur", nameArabic: "التكاثر", nameTranslation: "التكاثر", revelation: "Meccan", versesCount: 8, pages: [600, 600], juz: [30] },
  { number: 103, name: "Al-Asr", nameArabic: "العصر", nameTranslation: "العصر", revelation: "Meccan", versesCount: 3, pages: [601, 601], juz: [30] },
  { number: 104, name: "Al-Humazah", nameArabic: "الهمزة", nameTranslation: "الهمزة", revelation: "Meccan", versesCount: 9, pages: [601, 601], juz: [30] },
  { number: 105, name: "Al-Fil", nameArabic: "الفيل", nameTranslation: "الفيل", revelation: "Meccan", versesCount: 5, pages: [601, 601], juz: [30] },
  { number: 106, name: "Quraysh", nameArabic: "قريش", nameTranslation: "قريش", revelation: "Meccan", versesCount: 4, pages: [602, 602], juz: [30] },
  { number: 107, name: "Al-Ma'un", nameArabic: "الماعون", nameTranslation: "الماعون", revelation: "Meccan", versesCount: 7, pages: [602, 602], juz: [30] },
  { number: 108, name: "Al-Kawthar", nameArabic: "الكوثر", nameTranslation: "الكوثر", revelation: "Meccan", versesCount: 3, pages: [602, 602], juz: [30] },
  { number: 109, name: "Al-Kafirun", nameArabic: "الكافرون", nameTranslation: "الكافرون", revelation: "Meccan", versesCount: 6, pages: [603, 603], juz: [30] },
  { number: 110, name: "An-Nasr", nameArabic: "النصر", nameTranslation: "النصر", revelation: "Medinan", versesCount: 3, pages: [603, 603], juz: [30] },
  { number: 111, name: "Al-Masad", nameArabic: "المسد", nameTranslation: "المسد", revelation: "Meccan", versesCount: 5, pages: [603, 603], juz: [30] },
  { number: 112, name: "Al-Ikhlas", nameArabic: "الإخلاص", nameTranslation: "الإخلاص", revelation: "Meccan", versesCount: 4, pages: [604, 604], juz: [30] },
  { number: 113, name: "Al-Falaq", nameArabic: "الفلق", nameTranslation: "الفلق", revelation: "Meccan", versesCount: 5, pages: [604, 604], juz: [30] },
  { number: 114, name: "An-Nas", nameArabic: "الناس", nameTranslation: "الناس", revelation: "Meccan", versesCount: 6, pages: [604, 604], juz: [30] },
];

export const getSurah = (number: number): Surah | undefined =>
  SURAHS.find((s) => s.number === number);

export const JUZ_RANGES: { juz: number; surah: number; verse: number }[] = [
  { juz: 1, surah: 1, verse: 1 }, { juz: 2, surah: 2, verse: 142 },
  { juz: 3, surah: 2, verse: 253 }, { juz: 4, surah: 3, verse: 93 },
  { juz: 5, surah: 4, verse: 24 }, { juz: 6, surah: 4, verse: 148 },
  { juz: 7, surah: 5, verse: 82 }, { juz: 8, surah: 6, verse: 111 },
  { juz: 9, surah: 7, verse: 88 }, { juz: 10, surah: 8, verse: 41 },
  { juz: 11, surah: 9, verse: 93 }, { juz: 12, surah: 11, verse: 6 },
  { juz: 13, surah: 12, verse: 53 }, { juz: 14, surah: 15, verse: 1 },
  { juz: 15, surah: 17, verse: 1 }, { juz: 16, surah: 18, verse: 75 },
  { juz: 17, surah: 21, verse: 1 }, { juz: 18, surah: 23, verse: 1 },
  { juz: 19, surah: 25, verse: 21 }, { juz: 20, surah: 27, verse: 56 },
  { juz: 21, surah: 29, verse: 46 }, { juz: 22, surah: 33, verse: 31 },
  { juz: 23, surah: 36, verse: 28 }, { juz: 24, surah: 39, verse: 32 },
  { juz: 25, surah: 41, verse: 47 }, { juz: 26, surah: 46, verse: 1 },
  { juz: 27, surah: 51, verse: 31 }, { juz: 28, surah: 58, verse: 1 },
  { juz: 29, surah: 67, verse: 1 }, { juz: 30, surah: 78, verse: 1 },
];
